version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elknetwork
  kibana:
    image: kibana:7.7.0
    container_name: kibana
    hostname: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork
#  logstash:
#    image: logstash:7.7.0
#    container_name: logstash
#    hostname: logstash
#    ports:
#      - 9600:9600
#      - 8089:8089
#    volumes:
#      - .\logstash:/usr/share/logstash/pipeline/
#    links:
#      - elasticsearch:elasticsearch
#    depends_on:
#      - elasticsearch
#    networks:
#      - elknetwork
  filebeat:
      image: "docker.elastic.co/beats/filebeat:7.2.0"
      user: root
      volumes:
        - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        - /var/lib/docker:/var/lib/docker:ro
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - elknetwork
networks:
  elknetwork:
    driver: bridge
volumes:
  elasticsearch_data:

    #server url: http://localhost:15672
#user: guest
#pass: guest