server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

config:
  rabbitmq:
    exchange: ds.exchange
    queue: ds.queue
    routingKey: ds.routingkey